language: c++
cache: ccache

os:
  - osx
  - linux

compiler:
  - clang

addons:
  mariadb: '10.2'

install:
  - mkdir deps
  - cd deps
  - curl https://s3.us-east-2.amazonaws.com/v8-build/v8-build-$TRAVIS_OS_NAME-x64-release.tar.gz > v8-prebuilt.tar.gz
  - tar -xzf v8-prebuilt.tar.gz
  - mv build/ v8/
  - cd ../

script: 
  - mkdir build
  - cd build
  - cmake -DDOWNLOAD_PRE_BUILD_V8=on ..
  - make 
  - make install
  - cd ..
  - mkdir release
  - tar -czvf release/mysql-js-$TRAVIS_OS_NAME-x64-release.tar.gz build/libmysql-js.so deps/v8/icudtl.dat deps/v8/natives_blob.bin  deps/v8/snapshot_blob Loader.js script.js


deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_S3_BUCKET
  skip_cleanup: true
  local_dir: release
  region: $AWS_S3_REGION