language: c++
cache: ccache

sudo: required


jobs:
  include:
    - os: linux
      compiler: gcc
      install: 
       - sudo add-apt-repository ppa:pinepain/libv8-archived -y
       - sudo apt-get update -q
       - sudo apt-get install libv8-5.9-dev -y
       - sudo apt-get install mysqlclient-dev
    - os: osx
      compiler: clang
      install: brew install v8

addons:
  mariadb: '10.2'

script: 
  - mkdir build
  - cd build
  - cmake .. 
  - make 
  - make install
  - cd ..
  - mkdir release
  - tar -czvf release/mysql-js-$TRAVIS_OS_NAME-x64-release.tar.gz build/libmysql-js.so deps/v8/icudtl.dat deps/v8/natives_blob.bin  deps/v8/snapshot_blob Loader.js script.js


deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_S3_BUCKET
  skip_cleanup: true
  local_dir: release
  region: $AWS_S3_REGION