#!/usr/bin/env node
(function(){

    process.title = "deployJS";

    const commandLineArgs = require('command-line-args')
    const mysql = require("mysql");
    const readline = require('readline');

    const optionDefinitions = [
        { name: 'password', alias: 'p', type: String },
        { name: 'src', type: String, defaultOption: true },
        { name: 'user', alias: 'u', type: String },
        { name: 'database', alias: 'd', type: String },
        { name: 'help', alias: 'h', type: Boolean }

      ]
    const options = commandLineArgs(optionDefinitions)

    options.database = options.database || "test";
    options.user = options.user || require("os").userInfo().username;
   

    if(process.argv.length<3 || options.help)
    {
        console.log(" Usage: deployJS [options] <filename.js>");
        console.log("           --src               optional; for filename.js");
        console.log("           --help      -h      show this help");
        console.log("           --user      -u      mysql user name or current os user if ommited");
        console.log("           --password  -p      mysql password or prompt for it");
        console.log("           --database  -d      mysql database or test if ommited");
        process.exit(1);
    }
    
    
    var module_path = process.env.PWD +"/"+ options.src;
    var module = require(module_path);
    
    //deploy all functions into MySQL

    function CreateMySQLFunction(func_name,arg_nbr)
    {
        //create a MySQL Function from template
        /*
           CREATE FUNCTION `func_name` ( arg1 TEXT, arg2 TEXT,...)
             RETURNS TEXT
             DETERMINISTIC
             BEGIN
                DECLARE r TEXT;
                SET r = javascript("func_name",arg1,arg2,..);
                RETRUN r;
            END
         */

         var query = "CREATE FUNCTION ";
         query+= func_name;
         query+= ' (';
         var arg_list="";
         for (var i = 0; i< arg_nbr;++i)
         {
            if(i!=0) 
            {
                query+=",";
                arg_list+=",";
            }
            query+=" arg"+i;
            query+=" TEXT";  
            arg_list+="arg"+i;
         }
         query+=")";
         query+="\n RETURNS TEXT ";
         query+="\n DETERMINISTIC";
         query+="\n BEGIN";
         query+="\n  DECLARE r TEXT;";
         query+="\n  SET r = javascript("+'"'+func_name+'"';
         query+=" "+ arg_list +" );";
         query+="\n  RETURN r;";
         query+="\n END";

         return query;
    }


    function deploy(passwrd){
        var connection = mysql.createConnection({
            host     : 'localhost',
            user     : 'root',
            password : passwrd,
            database : options.database
          });
           
          connection.connect();
           
         
    
        var functions_names = Object.getOwnPropertyNames(module);
        var promises = functions_names.map(element => {
            return new Promise(function(resolve,reject){
                var query =CreateMySQLFunction(element, module[element].length);
                connection.query(query, function (error, results, fields) {
                    if(error) reject(error);
                    else{
                        console.log("function "+ element + " deployed." )
                    }
                });
            });
            
        });
        Promise.all(promises).catch(function(err){
            console.log(err);
        });
         
        connection.end();
      
       
    };

    if(options.password=== null)
    {
        const rl = readline.createInterface({
            input: process.stdin,
            output: process.stdout
           });
       
           rl.question('password: ' , (answer) => {
              
                deploy(answer);
                rl.close();
           });
    }
    else{
        deploy(options.password);
    }

   

})()